name: make_my_trip_admin_panel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^5.0.6996
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  flutter_isolate: ^2.0.2
  flutter_rating_bar: ^4.0.1


  #api call
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1

  #firebase services
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  firebase_storage: ^10.3.5
  cloud_firestore: ^3.4.4

  #state management ::: use cubit pattern
  flutter_bloc: ^8.0.1

  #for state checking ::: use equatable or freezed package
  equatable: ^2.0.3

  #error handling
  dartz: ^0.10.1

  #for reactive programming
  rxdart: ^0.27.5

  #dependency injection
  get_it: ^7.2.0

  #for dateTime conversions
  intl: ^0.17.0

  #for Animation effects
  page_transition: ^2.0.9
  shimmer: ^2.0.0

  #for checking internet connectivity
  connectivity_plus: ^2.3.6+1
  html_editor_enhanced: ^2.2.0+1-dev.1
  file_picker: ^4.6.1
  firebase_remote_config: ^2.0.14
dev_dependencies:
  flutter_test:
    sdk: flutter

  #for lint checks
  flutter_lints: ^2.0.0

  #use this for testing
  mockito: 5.3.0
  build_runner: 2.2.0
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true

  #your all local assets
  assets:
    - assets/
    - assets/img/

  # font family of app
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
