# This is a basic workflow to help you get started with Actions

name: make_my_trip_dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" , "main" ]
  pull_request:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Create file
        run: cat ./make_my_trip/android/app/google-services.json | base64
      - name: Provide Firebase Android
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./make_my_trip/android/app/google-services.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.1'
      - name: basic config
        run: | 
          cd ./make_my_trip
          flutter pub get
          flutter pub run build_runner build
          # flutter format --set-exit-if-changed
          # flutter analyze
          # flutter test
          flutter build apk
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: apk-build
          path: ./make_my_trip/build/app/outputs/apk/release
      - name: Deploy
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.4
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APPID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          releaseNotes: "a new travelsy version"
          file: ./make_my_trip/build/app/outputs/apk/release/app-release.apk
